from . import tipos_seccion
from . import section_type
from . import product_category
from . import res_currency
from . import paper_material
from . import finishing_service
from . import print_quote
from . import quote_tiraje
from . import quote_interior
from . import quote_papel
from . import quote_placa
from . import quote_offset
from . import quote_acabado
from . import quote_doblado
from . import quote_alce
from . import quote_cosido
from . import quote_encuadernado
from . import quote_empaquetado
from . import quote_troquelado
from . import quote_corte
from . import quote_transporte
from . import process_template
from . import production_process
from . import mrp_production
from . import invoice_production
from . import invoice_edi
from . import detraccion_tipo
from . import detraccion
